service: k2-oracle

frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-plugin-ifelse

custom:
  serverless-offline:
    host: 0.0.0.0
  currentStage: ${opt:stage, self:provider.stage}
  serverlessIfElse:
    - If: '"${self:custom.currentStage}" == "local"'
      Set:
        functions.oracle.handler: ./handler.oracle

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1

  ecr:
    images:
      k2_oracle:
        path: ./

functions:
  oracle:
    image:
      name: k2_oracle
      command:
        - handler.oracle
      entryPoint:
        - "/lambda-entrypoint.sh"
    memorySize: 3500
    timeout: 30
    events:
      - http:
          path: oracle
          method: get
          cors: true
